# .github/workflows/deploy.yml
name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # or master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v3
      - uses: actions/upload-artifact@v3
        with:
          path: './'  # or your site output directory
      - uses: actions/deploy-pages@v2
